### ISSUE TITLE
gh-pages commits have bad author

### ISSUE THREAD

**Issue by pjking07** [chriskrycho/v4.chriskrycho.com#24]
The author for these commits reads as `b'Christopher Krycho'` with an error message of "Invalid author email. If this commit was made by you, check your local git email setting."

e.g. https://github.com/chriskrycho/chriskrycho.com/commit/6500dd09a99caa3282bd7e76d4f7b654267d9c3c, but the same problem exists with every commit on this branch. I'm guessing there is some error in the configuration you're using for simultaneously posting to master and (the output) to gh-pages.

**Comment by chriskrycho** [comment]
Yeah, there's something wrong with the `ghp-import` script I'm using; I haven't had a chance to check it yet. It's handling the string incorrectly for some reason.
